ALTER TABLE  `COMMERCIAL_PROVIDER_INVOICE` ADD  `file_md5_hash` VARCHAR( 64 ) NULL DEFAULT NULL;
ALTER TABLE  `COMMERCIAL_PROVIDER_INVOICE` ADD INDEX (  `file_md5_hash` ) ;
ALTER TABLE  `COMMERCIAL_COMPANY_CONFIG` ADD  `imprint` TEXT NULL DEFAULT NULL ,
ADD  `terms` LONGTEXT NULL DEFAULT NULL;
ALTER TABLE  `COMMERCIAL_COMPANY_CONFIG` ADD  `terms_font_size` DECIMAL( 3, 1 ) NOT NULL DEFAULT  '8';