CREATE TABLE IF NOT EXISTS `COMMERCIAL_TIME_CREDIT` (
  `commercial_document_id` mediumint(9) NOT NULL,
  `credit_hours` time DEFAULT NULL,
  PRIMARY KEY (`commercial_document_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
ALTER TABLE  `COMMERCIAL_TIME_CREDIT` CHANGE  `credit_hours`  `credit_minutes` MEDIUMINT NOT NULL DEFAULT  '0';

--
ALTER TABLE `COMMERCIAL_TIME_CREDIT`
  ADD CONSTRAINT `COMMERCIAL_TIME_CREDIT_ibfk_1` FOREIGN KEY (`commercial_document_id`) REFERENCES `COMMERCIAL_COMMERCIAL_DOCUMENT` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

